#!/bin/bash
# Prints .github/dependabot.yml, built from images.json: GitHub Actions updates for the workflows, and base-image
# (Dockerfile FROM) updates for every images/<tag> folder. test/check-images.sh fails when the file is out of date.
#   scripts/dependabot.sh > .github/dependabot.yml
# Run from the repository root (needs jq).
set -euo pipefail

images_json=${IMAGES_JSON:-images.json}

cat <<'EOF'
# Generated by scripts/dependabot.sh from images.json; test/check-images.sh fails when it is out of date.
# Regenerate after adding or removing an image: scripts/dependabot.sh > .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci

  # The FROM lines of every image. A tag names its runtime's version (java_8, python_3.12, dotnet_8), so only patch
  # updates of a base tag are proposed; moving a tag to a new major/minor base is a deliberate change (a new tag or
  # an edited Dockerfile). Floating tags (debian:bookworm-slim) are refreshed by the weekly rebuild instead.
  - package-ecosystem: docker
    directories:
EOF
jq -r '.images[].folder' "${images_json}" | LC_ALL=C sort | sed 's|^|      - /|'
cat <<'EOF'
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      base-images:
        patterns: ["*"]
    commit-message:
      prefix: images
EOF
